// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcffbwjybgvospzfzjvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZmZid2p5Ymd2b3NwemZ6anZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNjc5MjMsImV4cCI6MjA1NDk0MzkyM30.jPm5CmjPhxKERPE6TSiFeppNyrEgjba4uOJ0MWN3h70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);